// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoghlana.EF;

#nullable disable

namespace Educational_Medical_platform.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240918190926_QuestionsAndAnswers")]
    partial class QuestionsAndAnswers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Educational_Medical_platform.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cell",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tissue",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Organ",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mitochondria",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nucleus",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ribosome",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Protein synthesis",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Energy production",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "DNA replication",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Protects the cell",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "Stores DNA",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Produces energy",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Movement of water",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 14,
                            Description = "Transport of nutrients",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 15,
                            Description = "Protein synthesis",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 16,
                            Description = "Breaks down food",
                            IsCorrect = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 17,
                            Description = "Circulates blood",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 18,
                            Description = "Transports oxygen",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 19,
                            Description = "Through the walls of the intestines",
                            IsCorrect = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 20,
                            Description = "Via the bloodstream",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 21,
                            Description = "By chewing",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 22,
                            Description = "Mouth, esophagus, stomach",
                            IsCorrect = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 23,
                            Description = "Brain, heart, lungs",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 24,
                            Description = "Skin, muscles, bones",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 25,
                            Description = "They speed up chemical reactions",
                            IsCorrect = true,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 26,
                            Description = "They are absorbed",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 27,
                            Description = "They break down food",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 28,
                            Description = "The wave-like motion that moves food",
                            IsCorrect = true,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 29,
                            Description = "The absorption of nutrients",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 30,
                            Description = "The secretion of enzymes",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 31,
                            Description = "Organs and systems",
                            IsCorrect = true,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 32,
                            Description = "Cells only",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 33,
                            Description = "Muscles only",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 34,
                            Description = "By contracting and relaxing",
                            IsCorrect = true,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 35,
                            Description = "By sending signals",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 36,
                            Description = "By absorbing nutrients",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 37,
                            Description = "To understand the human body",
                            IsCorrect = true,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 38,
                            Description = "To pass exams",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 39,
                            Description = "To perform surgeries",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 40,
                            Description = "Nervous, muscular, skeletal",
                            IsCorrect = true,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 41,
                            Description = "Respiratory, circulatory",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 42,
                            Description = "Digestive, excretory",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 43,
                            Description = "Controls body functions",
                            IsCorrect = true,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 44,
                            Description = "Transports nutrients",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 45,
                            Description = "Provides energy",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 46,
                            Description = "To carry oxygen",
                            IsCorrect = true,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 47,
                            Description = "To fight infections",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 48,
                            Description = "To clot blood",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 49,
                            Description = "By recognizing pathogens",
                            IsCorrect = true,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 50,
                            Description = "By producing energy",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 51,
                            Description = "By storing nutrients",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 52,
                            Description = "Interphase, mitosis, cytokinesis",
                            IsCorrect = true,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 53,
                            Description = "Prophase, metaphase, anaphase",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 54,
                            Description = "Meiosis only",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 55,
                            Description = "Programmed cell death",
                            IsCorrect = true,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 56,
                            Description = "Cell growth",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 57,
                            Description = "Cell division",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 58,
                            Description = "Carries genetic information",
                            IsCorrect = true,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 59,
                            Description = "Produces energy",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 60,
                            Description = "Fights diseases",
                            IsCorrect = false,
                            QuestionId = 20
                        });
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LikesNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Conclusion = "Understanding human anatomy is essential for medical professionals and enthusiasts alike.",
                            Content = "This blog covers the basics of human anatomy...",
                            ImageURL = "/Images/Blogs/blog1.jpg",
                            Intro = "Anatomy is the branch of biology concerned with the study of the structure of organisms and their parts.",
                            LikesNumber = 10,
                            Title = "Introduction to Human Anatomy"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Conclusion = "The study of comparative anatomy is crucial for evolutionary biology and understanding the functional adaptations of organisms.",
                            Content = "This blog explores comparative anatomy across species...",
                            ImageURL = "/Images/Blogs/blog1.jpg",
                            Intro = "Comparative anatomy allows us to understand the similarities and differences between different organisms.",
                            LikesNumber = 15,
                            Title = "Advanced Comparative Anatomy"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Conclusion = "A deep understanding of cell physiology is vital for advancements in medical science.",
                            Content = "Understanding the basics of cell physiology...",
                            ImageURL = "/Images/Blogs/blog1.jpg",
                            Intro = "Cell physiology is the study of the functions of cells and their components.",
                            LikesNumber = 20,
                            Title = "Fundamentals of Cell Physiology"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Conclusion = "This overview serves as a foundational step towards more detailed studies of specific systems.",
                            Content = "This blog provides an overview of human anatomy...",
                            ImageURL = "/Images/Blogs/blog1.jpg",
                            Intro = "An overview of human anatomy highlights the complexity and organization of the human body.",
                            LikesNumber = 5,
                            SubCategoryId = 1,
                            Title = "Human Anatomy Overview"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Conclusion = "Grasping systemic physiology is crucial for understanding how the body maintains homeostasis.",
                            Content = "An introductory blog on systemic physiology...",
                            ImageURL = "/Images/Blogs/blog1.jpg",
                            Intro = "Systemic physiology studies the functions of various systems within the body.",
                            LikesNumber = 8,
                            SubCategoryId = 4,
                            Title = "Systemic Physiology Basics"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Conclusion = "Understanding these applications is essential for safe and effective patient care.",
                            Content = "Exploring clinical applications in pharmacology...",
                            ImageURL = "/Images/Blogs/blog1.jpg",
                            Intro = "Pharmacology focuses on the interactions between drugs and living organisms.",
                            LikesNumber = 12,
                            SubCategoryId = 5,
                            Title = "Clinical Applications of Pharmacology"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Conclusion = "A solid grasp of pathology is necessary for any healthcare professional.",
                            Content = "A comprehensive overview of pathology...",
                            ImageURL = "/Images/Blogs/blog1.jpg",
                            Intro = "Pathology is the study of disease, its causes, and effects on the body.",
                            LikesNumber = 7,
                            SubCategoryId = 7,
                            Title = "Pathology: An Overview"
                        });
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Blog_User_Likes", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BlogId");

                    b.HasIndex("BlogId");

                    b.ToTable("Blog_User_Likes");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anatomy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physiology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pharmacology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pathology"
                        });
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.CertificateDetails", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CertifiedHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CertificateDetails");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("DurationInhours")
                        .HasColumnType("real");

                    b.Property<string>("Preview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationInhours = 10f,
                            SubCategoryId = 1,
                            Title = "physiology"
                        },
                        new
                        {
                            Id = 2,
                            DurationInhours = 20f,
                            SubCategoryId = 1,
                            Title = "anatomy"
                        },
                        new
                        {
                            Id = 3,
                            DurationInhours = 30f,
                            SubCategoryId = 1,
                            Title = "histology"
                        });
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Objectives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "Enhancing medical skills"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Description = "Enhancing physiology knowledge"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Description = "increasing job opportunities"
                        });
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlogId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "What is the basic unit of life?"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Description = "Which organelle is known as the powerhouse of the cell?"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            Description = "What is the function of ribosomes?"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Description = "What is the role of the cell membrane?"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            Description = "What is osmosis?"
                        },
                        new
                        {
                            Id = 6,
                            Description = "What is the primary function of the digestive system?",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "How does the body absorb nutrients?",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "What are the main components of the digestive system?",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "What is the role of enzymes in digestion?",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "What is the process of peristalsis?",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 11,
                            BlogId = 1,
                            Description = "What are the key structures of the human body?"
                        },
                        new
                        {
                            Id = 12,
                            BlogId = 1,
                            Description = "How does the muscular system work?"
                        },
                        new
                        {
                            Id = 13,
                            BlogId = 2,
                            Description = "What is the importance of studying anatomy?"
                        },
                        new
                        {
                            Id = 14,
                            BlogId = 2,
                            Description = "What are the different systems of the human body?"
                        },
                        new
                        {
                            Id = 15,
                            BlogId = 3,
                            Description = "What role does the nervous system play in body functions?"
                        },
                        new
                        {
                            Id = 16,
                            Description = "What is the primary function of red blood cells?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 17,
                            Description = "How does the immune system protect the body?",
                            TestId = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "What are the stages of the cell cycle?",
                            TestId = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "What is apoptosis?",
                            TestId = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "What role does DNA play in inheritance?",
                            TestId = 2
                        });
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Requirements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "being medical student"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Description = "having laptop"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            Description = "buying premium package"
                        });
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.StandardTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Fullmark")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StandardTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationInMinutes = 60,
                            Fullmark = 100,
                            Title = "Test1"
                        },
                        new
                        {
                            Id = 2,
                            DurationInMinutes = 100,
                            Fullmark = 150,
                            Title = "Test2"
                        },
                        new
                        {
                            Id = 3,
                            DurationInMinutes = 200,
                            Fullmark = 300,
                            Title = "Test3"
                        });
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Student_Courses", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CertificateDetailsCourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CertificateDetailsStudentId")
                        .HasColumnType("int");

                    b.Property<float?>("Degree")
                        .HasColumnType("real");

                    b.Property<int>("VideoNumber")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CertificateDetailsStudentId", "CertificateDetailsCourseId");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Human Anatomy"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Comparative Anatomy"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Cell Physiology"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Systemic Physiology"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Clinical Pharmacology"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Pharmacokinetics"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "General Pathology"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Systemic Pathology"
                        });
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Number = 1,
                            Title = "new video",
                            videoURL = "https://www.youtube.com/watch?v=4oThHBo2-Gs"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Number = 1,
                            Title = "old video",
                            videoURL = "https://www.youtube.com/watch?v=mgEAimOoyHk"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Number = 1,
                            Title = "funny video",
                            videoURL = "https://www.youtube.com/watch?v=zhCKr62s12w"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "952625cb-623b-4f8e-a426-c9e14ffe41bc",
                            ConcurrencyStamp = "9e9ef764-d672-42d8-99ee-93c2410d8ae0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "23978a1d-7823-4030-bd5d-ef7a0e6412a2",
                            ConcurrencyStamp = "df2d8409-ce61-4dac-ae75-b26fbbab27f2",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "ea3203f7-8571-4e45-b109-e593235f3420",
                            ConcurrencyStamp = "df2d8409-ce61-4dac-ae75-b26fbbab27f2",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Shoghlana.Core.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Admin", b =>
                {
                    b.HasOne("Shoghlana.Core.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Answer", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Blog", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Category", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Educational_Medical_platform.Models.SubCategory", "SubCategory")
                        .WithMany("Blogs")
                        .HasForeignKey("SubCategoryId");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Blog_User_Likes", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Blog", "Blog")
                        .WithMany("Likes")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoghlana.Core.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Book", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Educational_Medical_platform.Models.SubCategory", "SubCategory")
                        .WithMany("Books")
                        .HasForeignKey("SubCategoryId");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.CertificateDetails", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Educational_Medical_platform.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Course", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.SubCategory", "SubCategory")
                        .WithMany("Courses")
                        .HasForeignKey("SubCategoryId");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Instructor", b =>
                {
                    b.HasOne("Shoghlana.Core.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Objective", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Course", "Course")
                        .WithMany("Objectives")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Question", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Blog", "Blog")
                        .WithMany("Questions")
                        .HasForeignKey("BlogId");

                    b.HasOne("Educational_Medical_platform.Models.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("CourseId");

                    b.HasOne("Educational_Medical_platform.Models.SubCategory", "SubCategory")
                        .WithMany("QuestionBank")
                        .HasForeignKey("SubCategoryId");

                    b.HasOne("Educational_Medical_platform.Models.StandardTest", "Test")
                        .WithMany("Question")
                        .HasForeignKey("TestId");

                    b.Navigation("Blog");

                    b.Navigation("Course");

                    b.Navigation("SubCategory");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Requirement", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Course", "Course")
                        .WithMany("Requirements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Student", b =>
                {
                    b.HasOne("Shoghlana.Core.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Student_Courses", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Educational_Medical_platform.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Educational_Medical_platform.Models.CertificateDetails", "CertificateDetails")
                        .WithMany()
                        .HasForeignKey("CertificateDetailsStudentId", "CertificateDetailsCourseId");

                    b.Navigation("CertificateDetails");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.SubCategory", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Video", b =>
                {
                    b.HasOne("Educational_Medical_platform.Models.Course", "Course")
                        .WithMany("Videos")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Shoghlana.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Shoghlana.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoghlana.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Shoghlana.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Blog", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Category", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Books");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Course", b =>
                {
                    b.Navigation("Objectives");

                    b.Navigation("Questions");

                    b.Navigation("Requirements");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.StandardTest", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("Educational_Medical_platform.Models.SubCategory", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Books");

                    b.Navigation("Courses");

                    b.Navigation("QuestionBank");
                });
#pragma warning restore 612, 618
        }
    }
}
